#!/bin/sh

system_type="$(uname -s)"

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # set os settings
  sudo bash ~/.osx
fi

# Set up neovim
if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  nvim --headless -c "autocmd User Lazy install" -c "quitall"
fi

if [ ! -e "$HOME/.cargo/bin/rustup" ] && command -v rustup-init >/dev/null 2>&1; then
  echo "Installing RustUp"
  rustup-init -y --no-modify-path
fi
