setlocal autoindent
setlocal expandtab
setlocal colorcolumn=0
setlocal linebreak
setlocal nonumber
setlocal shiftwidth=4
setlocal spell
setlocal tabstop=4
setlocal wrap
let g:vim_markdown_frontmatter=1
